### ISSUE TITLE
List of body uncomplete

### ISSUE THREAD

**Issue by kenny94xxhell** [adam-ah/fusion360_parts_list#1]
Hello,

Thanks for the script. I succeded to run it on Fusion360.
But it only show a partial list of body. Does it work only with rectangular shaped body or with everything ?

There are several stage of sub component in my design. Does it work with many level of subcomponent ?

**Comment by kenny94xxhell** [comment]
Problem solved. Refer to change request.

**Comment by adam-ah** [comment]
I cannot see any PRs / change requests
